version: '3.8'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - './postgres-data:/var/lib/postgresql/data'
    ports:
      - '7432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dasfdsafsadfsdfs
      POSTGRES_DB: postgres

