version: "3.8"
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
  database:
    image: postgres:latest
    container_name:
      pg-rpc-endpoint
    environment:
      - POSTGRES_PASSWORD=dasfdsafsadfsdfs
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
    healthcheck:
      test:  [ "CMD", "pg_isready", "-q", "-d", "test", "-U", "postgres" ]
      interval: 3s
      timeout: 3s
      retries: 5
    ports:
      - "9432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  migrate:
    image: migrate/migrate
    volumes:
      - ./sql/psql:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://postgres:dasfdsafsadfsdfs@pg-rpc-endpoint:5432/test?sslmode=disable", "up" ]
    links:
      - database
    depends_on:
      database:
        condition: service_healthy

  rpc:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9545:9000"
    depends_on:
      - redis
      - database
    entrypoint: ["/app/rpc-endpoint"]
    command: >
      -redis "redis:6379"
      -signingKey "0x607a11b45a7219cc61a3d9c5fd08c7eebd602a6a19a977f8d3771d5711a550f2"
      -proxy "http://65.108.101.32:8545"
      -listen ":9000"
      -relayUrl "http://65.108.101.32:8545"
      -psql  "postgres://postgres:dasfdsafsadfsdfs@pg-rpc-endpoint:5432/test?sslmode=disable"

