version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    environment:
      LISTEN_ADDR: ":9000"
      REDIS_ADDR: "redis:6379"
      SIGNING_KEY: "0x607a11b45a7219cc61a3d9c5fd08c7eebd602a6a19a977f8d3771d5711a550f2"
      PROXY_URL: "http://65.108.101.32:8545"
      RELAY_URL: "http://65.108.101.32:8545"
      PSQL_CONN: "postgres://postgres:dasfdsafsadfsdfs@postgres:5432/postgres?sslmode=disable"
    ports:
      - "9000:9000"
    depends_on:
      - redis
      - postgres
    command: >
      /app/rpc-endpoint
      -redis $(REDIS_ADDR)
      -signingKey $(SIGNING_KEY)
      -proxy $(PROXY_URL)
      -listen $(LISTEN_ADDR)
      -relayUrl $(RELAY_URL)
      -psql $(PSQL_CONN)
